export type Source = {
  id: number;
  name: string;
  type: '官方公告' | '新聞' | '技術文件' | '影片' | '研究';
  title: string;
  url: string;
  date: string;
  note?: string;
  reliability?: '第一手官方來源' | '可信媒體' | '研究或技術來源' | '社群線索';
  reliabilityNote?: string;
};

export type Article = {
  id: string;
  image: string;
  imageAlt: string;
  category: string;
  title: string;
  summary: string;
  publishedAt: string;
  updatedAt: string;
  tags: string[];
  verified: boolean;
  evidenceLevel?: '官方確認' | '多方證實' | '可信報導' | '傳聞追蹤';
  evidenceNote?: string;
  body: { heading: string; text: string; citations: number[] }[];
  sources: Source[];
};

export const articles: Article[] = [
  {
    id: 'us-ai-regulation-political-gap-2026-09-15', image: '/news/ai-policy-regulation.png', imageAlt: 'AI 政策、國會與科技產業的彩色概念圖', category: '政策與治理',
    title: '美國科技領袖加強呼籲 AI 監管，但聯邦政治回應仍明顯分歧',
    summary: 'AP 報導指出，多位 AI 公司領袖要求加強監督，但白宮與國會對監管速度和方式仍缺乏共識。',
    publishedAt: '2026-09-15 12:01', updatedAt: '2026-09-15 15:25', tags: ['AI 監管','美國國會','政策'], verified: true,
    evidenceLevel: '可信報導', evidenceNote: '由具編輯制度與記者署名的 AP 採訪報導；政治人物與業界立場可核對，但政策尚未形成。',
    body: [
      { heading: '發生了什麼', text: 'AP 報導，多位科技領袖近期要求政府更積極處理先進 AI 風險，但美國行政部門與國會對監管方向仍存在明顯落差。', citations: [1] },
      { heading: '為什麼重要', text: '產業一方面推進模型能力，另一方面要求建立外部規則，顯示安全治理正從公司內部承諾進入政治協商。', citations: [1] },
      { heading: '仍待確認', text: '目前是立場與議程競爭，尚不能視為具體法案即將通過；需繼續觀察國會提案、聽證與行政措施。', citations: [1] },
    ],
    sources: [{ id: 1, name: 'Associated Press', type: '新聞', title: 'Tech CEOs call for AI regulation. Trump and Congress are not rushing to act', url: 'https://apnews.com/article/ai-regulation-trump-congress-tech-politics-d2d1bac8e8666c681937665596a4f603', date: '2026-09-15', reliability: '可信媒體', reliabilityNote: 'AP 有記者署名、採訪內容與編輯制度；政策結果仍須等待官方程序。' }],
  },
  {
    id: 'microsoft-student-ai-privacy-2026-09-15', image: '/news/taiwan-data-governance.png', imageAlt: '校園、學生資料與 AI 隱私保護的彩色概念圖', category: '教育與隱私',
    title: 'Microsoft 承諾限制學生資料用於 AI 訓練，校園工具開始面對更高隱私門檻',
    summary: 'AP 報導 Microsoft 與教師工會建立具約束力的校園 AI 隱私標準，包含第三方稽核、透明揭露與限制資料用途。',
    publishedAt: '2026-09-15 12:02', updatedAt: '2026-09-15 15:25', tags: ['Microsoft','教育 AI','學生隱私'], verified: true,
    evidenceLevel: '多方證實', evidenceNote: 'AP 報導援引 Microsoft、AFT 與公開協議；核心條款可回到協議與公司說法核對。',
    body: [
      { heading: '協議的核心', text: '依 AP 報導，Microsoft 承諾除狹窄安全例外外，不使用學生或教育工作者資料訓練 AI，也不得將資料用於廣告、出售或一般產品開發。', citations: [1] },
      { heading: '對學校的影響', text: '協議要求第三方稽核與面向家庭的清楚說明，代表學校採用 AI 工具時不能只比較功能，也必須審查資料流向與供應商責任。', citations: [1] },
      { heading: '限制', text: '這套標準目前主要適用 Microsoft 的相關校園合約，能否成為跨產業標準仍取決於其他大型供應商是否跟進。', citations: [1] },
    ],
    sources: [{ id: 1, name: 'Associated Press', type: '新聞', title: 'Microsoft commits to sweeping AI privacy rules for students', url: 'https://apnews.com/article/ai-school-student-data-privacy-microsoft-google-89b040631d635e0d8673f1e9aa9a6e28', date: '2026-09-15', reliability: '可信媒體', reliabilityNote: 'AP 具記者署名，並引用 Microsoft、教師工會與協議條款。' }],
  },
  {
    id: 'gates-foundation-ai-access-2026-09-15', image: '/news/ai-robotics-research.png', imageAlt: 'AI、醫療、教育與多語言公益應用的彩色概念圖', category: '產業與社會',
    title: 'Gates Foundation 承諾投入 10 億美元擴大 AI 取得，重點放在語言、健康與教育落差',
    summary: 'AP 報導基金會將在兩年內投入 10 億美元，支持在地語言模型、健康、教育與小農應用，同時警告 AI 可能擴大不平等。',
    publishedAt: '2026-09-15 12:03', updatedAt: '2026-09-15 15:25', tags: ['Gates Foundation','AI 公益','多語言'], verified: true,
    evidenceLevel: '可信報導', evidenceNote: '金額與用途來自 AP 對基金會年度報告及主管的採訪整理；後續實際撥款與成效仍需追蹤。',
    body: [
      { heading: '資金將用在哪裡', text: '基金會表示，10 億美元將在兩年內投入 AI 相關工作，包括在地語言資料與模型、健康成果、教育工具以及小農資訊服務。', citations: [1] },
      { heading: '市場意義', text: '這筆承諾把 AI 競爭從大型商業市場延伸到資源不足地區，也凸顯英文與少數主要語言以外的資料缺口。', citations: [1] },
      { heading: '後續觀察', text: '承諾金額不等於已產生成效；需要持續核對受款計畫、公開評估、當地治理與受益者實際使用情況。', citations: [1] },
    ],
    sources: [{ id: 1, name: 'Associated Press', type: '新聞', title: 'Gates Foundation warns AI could widen inequality as foundation pledges $1B', url: 'https://apnews.com/article/bill-gates-foundation-ai-united-nations-26ce25f9be20574a4fa04a5f983521ae', date: '2026-09-15', reliability: '可信媒體', reliabilityNote: 'AP 引用基金會年度報告與主管訪談；執行成效尚待後續資料。' }],
  },
  {
    id: 'microsoft-ai-code-of-conduct-2026-09-15', image: '/news/ai-agent-tools.png', imageAlt: 'AI 模型安全規則與人類監督的彩色概念圖', category: '安全與治理',
    title: 'Microsoft 公開模型行為規範，將網路攻擊、欺騙與逃避人類監督列為紅線',
    summary: 'TechCrunch 根據 Microsoft AI 官方文件報導，模型規範包含不可被個別任務覆蓋的最高原則與安全限制。',
    publishedAt: '2026-09-15 11:27', updatedAt: '2026-09-15 15:25', tags: ['Microsoft AI','模型規範','AI 安全'], verified: true,
    evidenceLevel: '多方證實', evidenceNote: '可信媒體報導可回溯至 Microsoft AI 官方原始文件，核心條文有第一手來源支持。',
    body: [
      { heading: '規範說了什麼', text: 'TechCrunch 報導，Microsoft AI 的模型行為規範要求模型支持人類、避免網路攻擊與深偽等行為，並禁止以欺騙、串通或自我強化方式逃避授權人員監督。', citations: [1,2] },
      { heading: '為什麼重要', text: '把模型最高原則寫成可公開檢查的文件，有助外界比較供應商的安全邊界，也為後續評測與事故追責提供基準。', citations: [1,2] },
      { heading: '限制', text: '公開規範描述的是設計目標，並不能單獨證明模型在所有情境都會遵守；仍需搭配獨立評測與事件揭露。', citations: [1,2] },
    ],
    sources: [
      { id: 1, name: 'TechCrunch', type: '新聞', title: "Microsoft's new AI 'code of conduct' tells models not to hack systems or trick humans", url: 'https://techcrunch.com/2026/09/14/microsofts-new-ai-code-of-conduct-tells-models-not-to-hack-systems-or-trick-humans/', date: '2026-09-15', reliability: '可信媒體', reliabilityNote: '具記者署名並直接連結 Microsoft AI 原始文件。' },
      { id: 2, name: 'Microsoft AI', type: '官方公告', title: 'MAI model code of conduct', url: 'https://microsoft.ai/', date: '2026-09-14', reliability: '第一手官方來源', reliabilityNote: '規範由 Microsoft AI 發布；實際遵循程度仍需外部評測。' },
    ],
  },
  {
    id: 'anthropic-enterprise-cost-controls',
    image: '/news/taiwan-data-governance.png',
    imageAlt: '企業團隊檢視 AI 使用量與成本分析的彩色概念圖',
    category: '企業應用',
    title: 'Anthropic 將企業 AI 成本管理推向日常營運，管理員可直接查看成員用量',
    summary:
      'Anthropic 的官方企業講座聚焦模型預設值、成員支出可視性、Analytics Chat 與 Analytics API，顯示生成式 AI 的採用焦點正從試用轉向可預測的營運成本。',
    publishedAt: '2026-09-15 11:00',
    updatedAt: '2026-09-15 14:55',
    tags: ['Anthropic', 'Claude Enterprise', '成本管理', 'Analytics API'],
    verified: true,
    evidenceLevel: '官方確認',
    evidenceNote: '事件日期與內容來自 Anthropic 官方活動頁面。',
    body: [
      {
        heading: '官方今天說明了什麼',
        text: 'Anthropic 在 9 月 15 日的官方企業講座中，示範如何透過模型預設值與權限、成員支出可視性、Analytics Chat，以及 Analytics API 的用量與成本報告，管理 Claude Enterprise 的消耗式計價。',
        citations: [1],
      },
      {
        heading: '為什麼值得注意',
        text: '當企業把生成式 AI 從少數人的試驗擴大到整個團隊，問題不再只有模型效果，也包含誰能使用哪些模型、支出如何被看見，以及異常用量能否及時處理。成本治理正在成為正式導入 AI 的基本能力。',
        citations: [1],
      },
      {
        heading: '解讀限制',
        text: '這是一場產品與營運實務講座，並非新模型發布，也沒有提供跨供應商的成本比較。實際節省幅度仍取決於各公司的工作負載、模型選擇與內部使用規範。',
        citations: [1],
      },
    ],
    sources: [
      {
        id: 1,
        name: 'Anthropic',
        type: '影片',
        title: 'Scaling Claude with Cost Controls',
        url: 'https://www.anthropic.com/webinars/scaling-claude-with-cost-controls-sept-2026',
        date: '2026-09-15',
        reliability: '第一手官方來源',
        reliabilityNote: '由 Anthropic 官方網站發布，可直接核對活動日期與議程。',
      },
    ],
  },
  {
    id: 'anthropic-cyber-evaluation-incidents',
    image: '/news/ai-agent-tools.png',
    imageAlt: 'AI 代理系統操作多種數位工具的彩色概念圖',
    category: '安全與治理',
    title:
      'Anthropic 公開四起模型誤連真實網路事件，長時間代理任務的授權邊界再受檢驗',
    summary:
      '官方調查指出，第三方測試環境設定錯誤讓模型接觸真實系統；事件同時暴露環境隔離與模型判斷授權範圍的雙重問題。',
    publishedAt: '2026-09-09 00:00',
    updatedAt: '2026-09-10 08:30',
    tags: ['AI 安全', '代理系統', '資安評測', 'Anthropic'],
    verified: true,
    body: [
      {
        heading: '官方調查確認了什麼',
        text: 'Anthropic 表示，四起事件都發生在同一個第三方建立的資安評測環境。模型原本被告知沒有網路連線，但環境設定錯誤使公開網路實際可用；測試中的模型也未套用正式產品使用的資安防護。',
        citations: [1, 2],
      },
      {
        heading: '為什麼不只是環境設定問題',
        text: '調查將問題分成兩層：外部環境未正確隔離，以及模型在長時間任務中忽略或誤解現實線索、沒有充分確認授權範圍。Anthropic 認為這些行為嚴重，但沒有發現模型協調其他代理、追求任務外目標或規避監督的證據。',
        citations: [1],
      },
      {
        heading: '接下來如何處理',
        text: 'Anthropic 已擴大監控、強化訓練與評測環境要求，並與獨立評測組織 METR 簽訂調查協議。官方同時強調，如何讓評測涵蓋真實部署中的各種失敗條件，仍是未解決的研究問題。',
        citations: [1, 3],
      },
    ],
    sources: [
      {
        id: 1,
        name: 'Anthropic',
        type: '研究',
        title: 'An alignment assessment of recent cybersecurity incidents',
        url: 'https://www.anthropic.com/research/alignment-assessment-cybersecurity-incidents',
        date: '2026-09-09',
      },
      {
        id: 2,
        name: 'Anthropic Research',
        type: '研究',
        title: 'Anthropic Research publications',
        url: 'https://www.anthropic.com/research',
        date: '2026-09-09',
      },
      {
        id: 3,
        name: 'METR',
        type: '研究',
        title: 'METR research and incident investigations',
        url: 'https://metr.org/',
        date: '2026-09-09',
        note: 'Anthropic 公告中指定的獨立調查機構。',
      },
    ],
  },
  {
    id: 'openai-foundation-board-safety',
    image: '/news/ai-policy-regulation.png',
    imageAlt: '天平、治理文件與 AI 晶片的彩色概念圖',
    category: '公司治理',
    title: 'OpenAI 基金會董事會增列 AI 對齊研究者，並納入安全與資安委員會',
    summary:
      'Paul Christiano 將加入 OpenAI Foundation Board，並參與負責全公司安全與資安監督的委員會。',
    publishedAt: '2026-09-09 00:00',
    updatedAt: '2026-09-10 08:30',
    tags: ['OpenAI', '公司治理', 'AI 對齊', '安全'],
    verified: true,
    body: [
      {
        heading: '人事與職責',
        text: 'OpenAI 宣布 Paul Christiano 加入基金會董事會，並在 OpenAI Group PBC 董事會擔任無表決權觀察員。他也將加入基金會董事會的安全與資安委員會。',
        citations: [1, 2],
      },
      {
        heading: '這項安排的重要性',
        text: '該委員會負責監督 OpenAI 整體的安全與資安實務。Christiano 曾領導 AI 對齊研究、參與人類回饋強化學習的早期工作，也曾在美國政府的 AI 標準與評測單位任職。',
        citations: [1],
      },
      {
        heading: '解讀時的限制',
        text: '這是一項治理與監督職務調整，不代表模型、安全政策或產品會立即改變；後續影響仍要從委員會公開決策與制度變化判斷。',
        citations: [1],
      },
    ],
    sources: [
      {
        id: 1,
        name: 'OpenAI',
        type: '官方公告',
        title: 'Paul Christiano joins OpenAI Foundation Board',
        url: 'https://openai.com/index/paul-christiano-joins-openai-foundation-board/',
        date: '2026-09-09',
      },
      {
        id: 2,
        name: 'OpenAI Newsroom',
        type: '官方公告',
        title: 'Recent company announcements',
        url: 'https://openai.com/news/company-announcements/',
        date: '2026-09-09',
      },
    ],
  },
  {
    id: 'tool-using-models',
    image: '/news/ai-agent-tools.png',
    imageAlt: '機器手臂操作多種數位工具的彩色概念圖',
    category: '模型與產品',
    title: 'AI 模型競爭轉向長時間任務與工具操作，實際成本仍待驗證',
    summary:
      '多家公司近期把更新重點放在代理任務、軟體操作與工作流程整合，但官方測試和真實使用仍有落差。',
    publishedAt: '2026-09-09 08:40',
    updatedAt: '2026-09-09 10:12',
    tags: ['AI Agent', '模型', '工具操作'],
    verified: true,
    body: [
      {
        heading: '發生了什麼',
        text: '多家 AI 公司將新版本重點集中在長時間任務、工具呼叫與跨軟體操作。官方資料顯示任務完成率提升，但不同測試的條件並不相同。',
        citations: [1, 2, 3],
      },
      {
        heading: '為什麼重要',
        text: '競爭焦點逐漸從單次回答，轉向能否穩定完成一整段工作流程。這會影響企業採用方式，也使可靠度、權限控制與成本變得更重要。',
        citations: [1, 3, 4],
      },
      {
        heading: '仍待確認',
        text: '目前資料多來自官方測試與少量媒體試用，尚不能把測試分數直接等同於真實工作環境的成果。',
        citations: [2, 4],
      },
    ],
    sources: [
      {
        id: 1,
        name: 'OpenAI',
        type: '官方公告',
        title: 'OpenAI News',
        url: 'https://openai.com/news/',
        date: '2026-09-08',
      },
      {
        id: 2,
        name: 'Anthropic',
        type: '官方公告',
        title: 'Anthropic Newsroom',
        url: 'https://www.anthropic.com/news',
        date: '2026-09-08',
      },
      {
        id: 3,
        name: 'Google DeepMind',
        type: '技術文件',
        title: 'Google DeepMind Blog',
        url: 'https://deepmind.google/blog/',
        date: '2026-09-08',
      },
      {
        id: 4,
        name: 'MIT Technology Review',
        type: '新聞',
        title: 'Artificial intelligence',
        url: 'https://www.technologyreview.com/topic/artificial-intelligence/',
        date: '2026-09-09',
      },
    ],
  },
  {
    id: 'video-generation-control',
    image: '/news/video-generation-editing.png',
    imageAlt: '影片剪輯時間軸與人物一致性的彩色概念圖',
    category: '影像與影片',
    title: '影片生成工具的下一場競爭：角色一致性、局部修改與工作流程整合',
    summary:
      '最新工具不再只比較解析度，而是開始解決創作者如何修改、延續與管理生成素材。',
    publishedAt: '2026-09-09 07:55',
    updatedAt: '2026-09-09 09:30',
    tags: ['影片生成', '創作者', '影像'],
    verified: true,
    body: [
      {
        heading: '市場出現什麼變化',
        text: '產品更新開始強調鏡頭延續、角色一致性與局部修改，讓生成內容更容易進入正式製作流程。',
        citations: [1, 2],
      },
      {
        heading: '對創作者的影響',
        text: '真正的效率差異將取決於修改成本、輸出穩定度與商用授權，而不只是示範影片看起來是否逼真。',
        citations: [2, 3],
      },
    ],
    sources: [
      {
        id: 1,
        name: 'Google DeepMind',
        type: '官方公告',
        title: 'Models and product updates',
        url: 'https://deepmind.google/blog/',
        date: '2026-09-08',
      },
      {
        id: 2,
        name: 'Adobe Blog',
        type: '官方公告',
        title: 'Digital media updates',
        url: 'https://blog.adobe.com/',
        date: '2026-09-08',
      },
      {
        id: 3,
        name: 'Ars Technica',
        type: '新聞',
        title: 'AI coverage',
        url: 'https://arstechnica.com/ai/',
        date: '2026-09-09',
      },
    ],
  },
  {
    id: 'taiwan-ai-governance',
    image: '/news/taiwan-data-governance.png',
    imageAlt: '台灣企業資料治理與伺服器安全的彩色概念圖',
    category: '台灣產業',
    title: '台灣企業導入 AI 的焦點，正從試用工具轉向資料治理與實際效益',
    summary: '公開案例顯示，企業開始更在意資料權限、導入流程、成本與成效衡量。',
    publishedAt: '2026-09-08 17:20',
    updatedAt: '2026-09-09 08:15',
    tags: ['台灣', '企業應用', '治理'],
    verified: true,
    body: [
      {
        heading: '導入重點改變',
        text: '企業關注點逐漸從是否能使用生成式 AI，轉向資料能否安全進入流程，以及成果能否持續被衡量。',
        citations: [1, 2],
      },
      {
        heading: '接下來值得觀察',
        text: '人才培訓、內部資料品質與供應商鎖定，將比單次展示更影響長期成果。',
        citations: [2, 3],
      },
    ],
    sources: [
      {
        id: 1,
        name: '數位發展部',
        type: '官方公告',
        title: '政策與新聞公告',
        url: 'https://moda.gov.tw/',
        date: '2026-09-08',
      },
      {
        id: 2,
        name: 'iThome',
        type: '新聞',
        title: 'AI 與企業應用',
        url: 'https://www.ithome.com.tw/',
        date: '2026-09-08',
      },
      {
        id: 3,
        name: '國科會',
        type: '研究',
        title: '人工智慧相關計畫',
        url: 'https://www.nstc.gov.tw/',
        date: '2026-09-07',
      },
    ],
  },
  {
    id: 'open-source-models',
    image: '/news/open-source-ecosystem.png',
    imageAlt: '由模組構成的開源 AI 生態系彩色概念圖',
    category: '開源生態',
    title: '開源 AI 專案持續增加，評估重點應回到授權、維護與部署成本',
    summary:
      '下載量和排行榜只能提供部分訊號，真正採用前仍需確認授權條款與維護狀況。',
    publishedAt: '2026-09-08 14:05',
    updatedAt: '2026-09-08 18:10',
    tags: ['開源', 'GitHub', 'Hugging Face'],
    verified: true,
    body: [
      {
        heading: '如何判斷值得使用',
        text: '除了能力測試，也要檢查授權、更新頻率、社群維護與安全公告。',
        citations: [1, 2],
      },
    ],
    sources: [
      {
        id: 1,
        name: 'Hugging Face',
        type: '技術文件',
        title: 'Models and papers',
        url: 'https://huggingface.co/',
        date: '2026-09-08',
      },
      {
        id: 2,
        name: 'GitHub',
        type: '技術文件',
        title: 'Trending repositories',
        url: 'https://github.com/trending',
        date: '2026-09-08',
      },
    ],
  },
  {
    id: 'ai-compute-infrastructure',
    image: '/news/ai-compute-infrastructure.png',
    imageAlt: 'AI 晶片與大型資料中心的彩色概念圖',
    category: '算力與晶片',
    title: 'AI 基礎設施競爭擴大，電力、散熱與供應鏈成為部署關鍵',
    summary:
      '模型能力之外，資料中心建置速度、能源效率與晶片供應正直接影響 AI 服務的成本與規模。',
    publishedAt: '2026-09-08 12:30',
    updatedAt: '2026-09-08 16:45',
    tags: ['AI 晶片', '資料中心', '算力'],
    verified: true,
    body: [
      {
        heading: '競爭延伸到基礎設施',
        text: 'AI 服務的擴張不只依賴模型，也受晶片供應、機房電力與散熱能力限制。企業評估部署時，開始把整體營運成本納入比較。',
        citations: [1, 2],
      },
      {
        heading: '值得持續追蹤',
        text: '供應鏈交期、能源來源與不同加速器之間的軟體相容性，將影響新服務實際上線的時間。',
        citations: [1, 3],
      },
    ],
    sources: [
      {
        id: 1,
        name: 'NVIDIA',
        type: '官方公告',
        title: 'Data Center News',
        url: 'https://nvidianews.nvidia.com/',
        date: '2026-09-08',
      },
      {
        id: 2,
        name: 'AMD',
        type: '官方公告',
        title: 'AMD Newsroom',
        url: 'https://www.amd.com/en/newsroom.html',
        date: '2026-09-08',
      },
      {
        id: 3,
        name: 'IEEE Spectrum',
        type: '新聞',
        title: 'Artificial Intelligence',
        url: 'https://spectrum.ieee.org/artificial-intelligence',
        date: '2026-09-08',
      },
    ],
  },
  {
    id: 'ai-policy-regulation',
    image: '/news/ai-policy-regulation.png',
    imageAlt: '天平、文件與 AI 晶片構成的政策監管彩色概念圖',
    category: '政策與治理',
    title: 'AI 規範進入落地階段，企業需要把透明度要求轉成內部流程',
    summary:
      '政策討論逐步轉向執行細節，資料紀錄、風險分級與使用者告知將成為產品團隊的日常工作。',
    publishedAt: '2026-09-08 10:10',
    updatedAt: '2026-09-08 15:20',
    tags: ['AI 治理', '法規', '透明度'],
    verified: true,
    body: [
      {
        heading: '從原則走向執行',
        text: '監管要求不再只有抽象原則，產品團隊必須能說明資料來源、模型用途、風險評估與人工覆核方式。',
        citations: [1, 2],
      },
    ],
    sources: [
      {
        id: 1,
        name: 'European Commission',
        type: '官方公告',
        title: 'AI policy',
        url: 'https://digital-strategy.ec.europa.eu/en/policies/artificial-intelligence',
        date: '2026-09-08',
      },
      {
        id: 2,
        name: 'NIST',
        type: '技術文件',
        title: 'AI Risk Management Framework',
        url: 'https://www.nist.gov/itl/ai-risk-management-framework',
        date: '2026-09-08',
      },
    ],
  },
  {
    id: 'ai-robotics-research',
    image: '/news/ai-robotics-research.png',
    imageAlt: '研究人員在實驗室測試機器人的彩色概念圖',
    category: '研究與機器人',
    title: '機器人研究加速整合視覺與語言模型，可靠操作仍是核心門檻',
    summary:
      '研究進展讓機器人更容易理解指令與環境，但在陌生場景中保持安全、穩定仍需更多驗證。',
    publishedAt: '2026-09-07 19:40',
    updatedAt: '2026-09-08 09:15',
    tags: ['機器人', '研究', '多模態'],
    verified: true,
    body: [
      {
        heading: '能力正在整合',
        text: '視覺、語言與動作模型的結合，讓機器人能用更自然的方式接收任務，並根據環境調整步驟。',
        citations: [1, 2],
      },
      {
        heading: '距離大規模應用還有什麼',
        text: '長時間可靠度、安全停止機制與跨場景泛化，是從實驗展示走向日常部署前必須持續檢驗的項目。',
        citations: [1, 2],
      },
    ],
    sources: [
      {
        id: 1,
        name: 'Google DeepMind',
        type: '研究',
        title: 'Robotics research',
        url: 'https://deepmind.google/research/',
        date: '2026-09-07',
      },
      {
        id: 2,
        name: 'MIT CSAIL',
        type: '研究',
        title: 'Robotics',
        url: 'https://www.csail.mit.edu/research/robotics',
        date: '2026-09-07',
      },
    ],
  },
  {
    id: 'ai-creative-workflow',
    image: '/news/ai-creative-workflow.png',
    imageAlt: '攝影師在工作室使用 AI 後製影像的彩色概念圖',
    category: '創意工作',
    title: '生成式 AI 進入創意後製流程，效率提升也帶來來源標示需求',
    summary:
      '攝影與設計工具把生成、修補與選片整合進既有流程，團隊也開始建立素材授權與修改紀錄。',
    publishedAt: '2026-09-07 15:25',
    updatedAt: '2026-09-07 18:00',
    tags: ['攝影', '設計', '工作流程'],
    verified: true,
    body: [
      {
        heading: '工具如何改變流程',
        text: '生成式功能逐漸從獨立網站進入編修軟體，創作者可以在同一流程完成選片、局部修補與版本比較。',
        citations: [1, 2],
      },
      {
        heading: '不能忽略的管理問題',
        text: '商業團隊仍需確認素材授權、保留修改紀錄，並在需要時清楚揭露 AI 參與程度。',
        citations: [1, 2],
      },
    ],
    sources: [
      {
        id: 1,
        name: 'Adobe',
        type: '官方公告',
        title: 'Creative Cloud News',
        url: 'https://blog.adobe.com/en/topics/creative-cloud',
        date: '2026-09-07',
      },
      {
        id: 2,
        name: 'Content Authenticity Initiative',
        type: '技術文件',
        title: 'Content Credentials',
        url: 'https://contentauthenticity.org/',
        date: '2026-09-07',
      },
    ],
  },
];

export const calendarEvents = [
  {
    id: 24,
    date: '2026-03-31',
    title: 'OpenAI 完成 1,220 億美元新一輪融資',
    type: '產業',
    company: 'OpenAI',
    status: '已確認',
    format: '線上',
    source: 'https://openai.com/index/accelerating-the-next-phase-ai/',
  },
  {
    id: 25,
    date: '2026-04-16',
    title: 'Anthropic 發布 Claude Opus 4.7',
    type: '模型',
    company: 'Anthropic',
    status: '已確認',
    format: '線上',
    source: 'https://www.anthropic.com/news/claude-opus-4-7',
  },
  {
    id: 26,
    date: '2026-04-24',
    title: 'Google 四月 Gemini 功能更新（Gemini Drop）上線',
    type: '產品更新',
    company: 'Google',
    status: '已確認',
    format: '線上',
    source:
      'https://blog.google/innovation-and-ai/products/gemini-app/gemini-drop-april-2026/',
  },
  {
    id: 27,
    date: '2026-05-19',
    title: 'Google I/O 2026：Gemini 3.5 Flash 與 Gemini Omni 發布',
    type: '模型',
    company: 'Google',
    status: '已確認',
    format: '混合',
    source:
      'https://blog.google/innovation-and-ai/technology/developers-tools/google-io-2026-collection/',
  },
  {
    id: 28,
    date: '2026-05-28',
    title: 'Anthropic 完成 650 億美元 H 輪融資（Series H）',
    type: '產業',
    company: 'Anthropic',
    status: '已確認',
    format: '線上',
    source: 'https://www.anthropic.com/news/series-h',
  },
  {
    id: 29,
    date: '2026-06-09',
    title: 'Anthropic 發布 Claude Fable 5 與 Mythos 5',
    type: '模型',
    company: 'Anthropic',
    status: '已確認',
    format: '線上',
    source: 'https://www.anthropic.com/news/claude-fable-5-mythos-5',
  },
  {
    id: 30,
    date: '2026-06-12',
    title: 'Claude Fable 5 與 Mythos 5 暫停提供存取',
    type: '停止服務',
    company: 'Anthropic',
    status: '已確認',
    format: '線上',
    source: 'https://www.anthropic.com/news/claude-fable-5-mythos-5',
  },
  {
    id: 31,
    date: '2026-06-30',
    title: 'Anthropic 發布 Claude Sonnet 5',
    type: '模型',
    company: 'Anthropic',
    status: '已確認',
    format: '線上',
    source: 'https://www.anthropic.com/news',
  },
  {
    id: 32,
    date: '2026-07-01',
    title: 'Claude Fable 5 與 Mythos 5 恢復全球存取',
    type: '產品更新',
    company: 'Anthropic',
    status: '已確認',
    format: '線上',
    source: 'https://www.anthropic.com/news/redeploying-fable-5',
  },
  {
    id: 33,
    date: '2026-07-24',
    title: 'Anthropic 發布 Claude Opus 5',
    type: '模型',
    company: 'Anthropic',
    status: '已確認',
    format: '線上',
    source: 'https://www.anthropic.com/news',
  },
  {
    id: 34,
    date: '2026-08-04',
    title: 'Google 公布 Gemini 3.6 Flash 與 Robotics ER 2',
    type: '模型',
    company: 'Google',
    status: '已確認',
    format: '線上',
    source:
      'https://blog.google/innovation-and-ai/technology/ai/google-ai-updates-july-2026/',
  },
  {
    id: 35,
    date: '2026-08-14',
    title: 'Anthropic 公布 Claude 文字浮水印機制',
    type: '產品更新',
    company: 'Anthropic',
    status: '已確認',
    format: '線上',
    source: 'https://www.anthropic.com/news',
  },
  {
    id: 1,
    date: '2026-09-09',
    title: 'EASA 2026 人工智慧日（AI Days）',
    type: '政策',
    company: 'EASA',
    status: '已確認',
    format: '混合',
    source:
      'https://www.easa.europa.eu/en/newsroom-and-events/events/easa-artificial-intelligence-days-2026',
  },
  {
    id: 2,
    date: '2026-09-10',
    title: 'IEEE 2026 金融工程與經濟計算智慧研討會（CIFEr）',
    type: '研究',
    company: 'IEEE',
    status: '已確認',
    format: '實體',
    source: 'https://ai.ieee.org/events/',
  },
  {
    id: 3,
    date: '2026-09-10',
    title: 'ITU 人工智慧與機器學習挑戰賽（AI/ML Challenge）：網路流量應用推論',
    type: '競賽',
    company: 'ITU AI for Good',
    status: '已確認',
    format: '混合',
    source: 'https://aiforgood.itu.int/',
  },
  {
    id: 4,
    date: '2026-09-14',
    title: '沙烏地阿拉伯人工智慧整備黑客松（AI Readiness Hackathon）',
    type: '競賽',
    company: 'ITU AI for Good',
    status: '已確認',
    format: '實體',
    source: 'https://aiforgood.itu.int/',
  },
  {
    id: 5,
    date: '2026-09-15',
    title: '2026 人工智慧基礎設施高峰會（AI Infra Summit）',
    type: '產業',
    company: 'NVIDIA Events',
    status: '已確認',
    format: '實體',
    source: 'https://www.nvidia.com/en-us/events/ai-infra-summit/',
  },
  {
    id: 6,
    date: '2026-09-15',
    title: 'IEEE 發展與學習國際研討會（ICDL）',
    type: '研究',
    company: 'IEEE',
    status: '已確認',
    format: '實體',
    source: 'https://ai.ieee.org/events/',
  },
  {
    id: 7,
    date: '2026-09-15',
    title: '運用機器學習偵測資通訊基礎設施（Machine Learning for ICT Infrastructure Detection）',
    type: '研究',
    company: 'ITU AI for Good',
    status: '已確認',
    format: '線上',
    source: 'https://aiforgood.itu.int/',
  },
  {
    id: 8,
    date: '2026-09-16',
    title: 'CLAIR 研究領導力與人工智慧研討會',
    type: '研究',
    company: 'CLAIR',
    status: '已確認',
    format: '實體',
    source: 'https://www.clair-conf.com/agenda',
  },
  {
    id: 9,
    date: '2026-09-19',
    title: 'Google 人工智慧教育工作者系列（AI Educator Series）線上活動',
    type: '教育',
    company: 'Google',
    status: '已確認',
    format: '線上',
    source:
      'https://blog.google/products-and-platforms/products/education/new-ai-educator-trainings-september-2026/',
  },
  {
    id: 10,
    date: '2026-09-21',
    title: '2026 國際人工智慧研討會（International AI Symposium）',
    type: '研究',
    company: 'ICAS',
    status: '已確認',
    format: '實體',
    source: 'https://ais2026.icas.events/',
  },
  {
    id: 11,
    date: '2026-09-22',
    title: 'NVIDIA 新加坡人工智慧日（AI Day Singapore）',
    type: '產業',
    company: 'NVIDIA',
    status: '已確認',
    format: '實體',
    source: 'https://www.nvidia.com/en-us/ai-days/',
  },
  {
    id: 12,
    date: '2026-09-22',
    title: '開放世界具身智慧（Open World Embodied Intelligence）',
    type: '研究',
    company: 'ITU AI for Good',
    status: '已確認',
    format: '混合',
    source: 'https://aiforgood.itu.int/',
  },
  {
    id: 13,
    date: '2026-10-01',
    title: 'IEEE 科技高峰會：合乎倫理的人工智慧（Ethical AI）',
    type: '政策',
    company: 'IEEE',
    status: '已確認',
    format: '實體',
    source: 'https://ai.ieee.org/',
  },
  {
    id: 14,
    date: '2026-10-04',
    title: 'IEEE 系統、人類與控制論研討會（SMC Conference）',
    type: '研究',
    company: 'IEEE',
    status: '已確認',
    format: '實體',
    source: 'https://ai.ieee.org/events/',
  },
  {
    id: 15,
    date: '2026-11-09',
    title: 'NVIDIA 首爾人工智慧日（AI Day Seoul）',
    type: '產業',
    company: 'NVIDIA',
    status: '已確認',
    format: '實體',
    source: 'https://www.nvidia.com/en-us/ai-days/',
  },
  {
    id: 16,
    date: '2026-12-06',
    title: 'NeurIPS 2026 與 NVIDIA 人工智慧研究展示',
    type: '研究',
    company: 'NeurIPS／NVIDIA',
    status: '已確認',
    format: '實體',
    source: 'https://www.nvidia.com/en-us/events/neurips/',
  },
  {
    id: 17,
    date: '2026-12-13',
    title: 'IEEE 量子人工智慧研討會（Quantum AI Conference）',
    type: '研究',
    company: 'IEEE',
    status: '已確認',
    format: '實體',
    source: 'https://ai.ieee.org/events/',
  },
  {
    id: 18,
    date: '2027-02-16',
    title: 'AAAI-27 人工智慧研討會',
    type: '研究',
    company: 'AAAI',
    status: '已確認',
    format: '實體',
    source: 'https://aaai.org/conference/aaai/aaai-27/',
  },
  {
    id: 19,
    date: '2027-03-01',
    title: '2027 巴塞隆納世界行動通訊大會（MWC Barcelona）',
    type: '產業',
    company: 'MWC／NVIDIA',
    status: '已確認',
    format: '實體',
    source: 'https://www.nvidia.com/en-us/events/mobile-world-congress/',
  },
  {
    id: 20,
    date: '2026-09-15',
    title: 'OpenAI Codex 社群聚會（台中）',
    type: '活動',
    company: 'OpenAI 開發者社群',
    status: '已確認',
    format: '實體',
    source: 'https://developers.openai.com/community/meetups?city=Taichung',
  },
  {
    id: 21,
    date: '2026-09-13',
    title: 'Azure 電腦視覺介面（Computer Vision API）v1.0–v3.1 停止支援',
    type: '停止服務',
    company: 'Microsoft Azure',
    status: '已確認',
    format: '線上',
    source:
      'https://learn.microsoft.com/en-us/lifecycle/end-of-support/end-of-support-2026',
  },
  {
    id: 22,
    date: '2026-09-13',
    title: 'Microsoft Foundry IQ 無伺服器服務（Serverless）開始計費',
    type: '產品更新',
    company: 'Microsoft Foundry',
    status: '已確認',
    format: '線上',
    source:
      'https://devblogs.microsoft.com/foundry/build-smarter-agents-faster-with-foundry-iq/',
  },
  {
    id: 23,
    date: '2026-10-01',
    title: 'Azure Anomaly Detector、Metrics Advisor 與 Personalizer 退役',
    type: '停止服務',
    company: 'Microsoft Azure',
    status: '已確認',
    format: '線上',
    source:
      'https://learn.microsoft.com/en-us/lifecycle/end-of-support/end-of-support-2026',
  },
];

export const dailyPoints = [
  {
    title: '長時間代理任務暴露環境隔離與授權判斷風險',
    text: 'Anthropic 公開四起資安評測事件；設定錯誤讓模型接觸真實網路，而模型也未充分辨識授權邊界。',
    articleId: 'anthropic-cyber-evaluation-incidents',
  },
  {
    title: 'OpenAI 調整基金會安全治理架構',
    text: 'AI 對齊研究者 Paul Christiano 加入基金會董事會與安全及資安委員會，但實際政策影響仍待後續公開決策觀察。',
    articleId: 'openai-foundation-board-safety',
  },
];

export const dailyBriefing = {
  date: '2026 年 9 月 15 日',
  updatedAt: '14:55',
  readingMinutes: 4,
  title: '企業 AI 進入營運期，成本可視性開始與模型能力同等重要',
  summary:
    '今天可直接核對的新資訊不多，最明確的官方訊號來自 Anthropic：企業導入 Claude 的重點，正從「能不能用」轉向「能不能穩定、透明地管理用量與成本」。',
  lead:
    '9 月 15 日沒有出現足以改變市場格局的新旗艦模型公告。今天值得注意的是企業 AI 的管理層面：Anthropic 用一場官方講座集中說明模型預設、成員支出、自然語言成本查詢與 Analytics API。這些功能看似屬於後台，但它們決定 AI 能否從少數人的試驗，擴大成可預測的日常工具。',
  sections: [
    {
      heading: '成本控制成為企業 AI 的正式產品能力',
      paragraphs: [
        {
          text: 'Anthropic 在今天的官方企業講座中，將 Claude Enterprise 的成本管理拆成幾個可操作環節：設定模型預設值與使用權限、查看個別成員支出、透過 Analytics Chat 以自然語言詢問成本，以及利用 Analytics API 產出用量與費用報告。官方主張這些設定可由單一管理員快速啟用。[1]',
          citations: [1],
        },
        {
          text: '這裡的關鍵不是某一個報表功能，而是成本資料開始被放進日常管理流程。當更多員工使用不同模型與代理工具，企業必須知道用量從哪裡產生、哪些工作值得更高成本，以及何時需要調整權限或模型選擇。',
          citations: [1],
        },
      ],
    },
    {
      heading: '市場競爭從模型分數延伸到可管理性',
      paragraphs: [
        {
          text: '企業採購生成式 AI 時，模型能力仍然重要，但決策條件已經增加。管理者還會比較權限、稽核、成本預測、部門分攤與資料治理。供應商若只能提供強模型，卻無法讓管理者理解支出與風險，就很難支撐大規模部署。',
          citations: [1],
        },
        {
          text: '不過，今天的資料主要來自 Anthropic 自己的產品說明，不能據此判定 Claude 的成本一定較低，也不能推論所有企業都能快速完成治理。真正的效果仍需要實際用量、工作成果與跨供應商比較。',
          citations: [1],
        },
      ],
    },
    {
      heading: '今天對市場與使用者代表什麼',
      paragraphs: [
        {
          text: '對企業使用者來說，最實際的做法是先建立基準：哪些團隊正在使用、每類任務平均花費多少、產出是否節省時間，以及高成本模型是否真的帶來更好結果。沒有基準，成本控制很容易退化成單純限制額度。',
          citations: [1],
        },
        {
          text: '接下來應觀察 Analytics API 的資料細度、權限邊界、異常提醒，以及企業是否能把成本與實際業務成果連在一起。若這些能力成熟，模型供應商的競爭將不只發生在回答品質，也會發生在誰能提供更可靠的營運控制。',
          citations: [1],
        },
      ],
    },
  ],
  conclusion:
    '今天沒有重大模型發布，但企業 AI 的方向仍有明確變化：可預測的成本、清楚的用量與能被管理的權限，正在從附加功能變成正式導入的基本條件。',
  sources: [
    {
      id: 1,
      name: 'Anthropic',
      title: 'Scaling Claude with Cost Controls',
      url: 'https://www.anthropic.com/webinars/scaling-claude-with-cost-controls-sept-2026',
      type: '官方講座',
    },
  ],
};
